# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2f8ca2cfd875436854505ad2bcfd80b1368be29d7a71a15bfda96abac1aa5eb2877b2e98432188892f3094510502e195c419e1d40148c94589e21f3aaff75b3

test:
  secret_key_base: b56f639239a60c9682cffdbe61d8992e6e8eb37e93f036ff42b0f9066d8a2f88bd0d552a5e126dde9a43c89933bfce6e7b8217842ff04a941a179bbb08f81c56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
